version: '3.8'
services:
  backend:
    build: ./devops-lsp/backend
    ports:
      - "5001:5000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  frontend:
    build: ./devops-lsp/frontend
    ports:
      - "3000:80" # Maps local port 3000 to container port 80
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5001

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"