apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elasticsearch-sysctl
  namespace: kube-system
  labels:
    k8s-app: elasticsearch-sysctl
spec:
  selector:
    matchLabels:
      name: elasticsearch-sysctl
  template:
    metadata:
      labels:
        name: elasticsearch-sysctl
    spec:
      containers:
      - name: sysctl-buddy
        image: busybox
        command:
        - sh
        - -c
        - |
          sysctl -w vm.max_map_count=262144
          echo "Fixed vm.max_map_count"
          sleep 36000
        securityContext:
          privileged: true