apiVersion: v1
kind: Service
metadata:
  name: frontend  # This matches the Ingress rule for path "/"
  annotations:
    # Specific check for the API
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/success-codes: "200"
spec:
  type: ClusterIP
  selector:
    app: frontend # Matches the label in Deployment
  ports:
    - protocol: TCP
      port: 80       # The Service port (Ingress talks to this)
      targetPort: 80 # The Container port (Application listens on this)