apiVersion: v1
kind: Service
metadata:
  name: frontend  # This matches the Ingress rule for path "/"
spec:
  type: ClusterIP
  selector:
    app: frontend # Matches the label in Deployment
  ports:
    - protocol: TCP
      port: 80       # The Service port (Ingress talks to this)
      targetPort: 80 # The Container port (Application listens on this)